Testing cypress tests

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -1,12 +1,78 @@
 name: End-to-end tests
-on: [push]
+on:
+    push:
+        # Triggers on push to stage or master
+        branches: [stage, master]
+    workflow_dispatch:
 jobs:
-  cypress-run:
-    runs-on: ubuntu-20.04
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-      # Install NPM dependencies, cache them correctly
-      # and run all Cypress tests
-      - name: Cypress E2E tests
-        uses: cypress-io/github-action@v2
+    cypress-run:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v3
+            # Install NPM dependencies, cache them correctly
+            # and run all Cypress tests
+            - name: Node.js ${{ matrix.node-version }}
+              uses: actions/setup-node@v1
+              with:
+                  node-version: ${{ matrix.node-version }}
+            - name: Start backend
+              run: |
+                  # install server
+                  cd server
+                  npm install
+                  npm install -g wait-on
+                  docker build -t danningyu/edrop_backend .
+
+                  # initialize server
+                  cd .. 
+                  touch deploy/test/backend_pwds.env
+                  RESET_DATABASE=Yes docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d
+
+                  echo "Waiting for database to start"
+                  wait-on tcp:3306 --timeout 25000
+                  echo "Database has started"
+
+                  # Wait for database to be reset
+                  set +e
+                  retries=5
+                  docker-compose -f docker-compose.yml -f docker-compose.test.yml logs | grep 'Done resetting database'
+                  while [[ $? -ne 0 && $retries -ne 0 ]]; do
+                    echo "Waiting for database reset to occur, will try again in 5 seconds"
+                    echo "$retries retries left"
+                    sleep 5
+                    retries=$(( $retries - 1 ))
+                    docker-compose -f docker-compose.yml -f docker-compose.test.yml logs | grep 'Done resetting database'
+                  done
+
+                  if [[ $retries -eq 0 ]]; then
+                    echo "Test failure: failed to reset database"
+                    exit 1
+                  else
+                    echo "Database has been reset"
+                  fi
+
+                  set -e
+
+                  # Restart backend without resetting database
+                  docker-compose -f docker-compose.yml -f docker-compose.test.yml down
+                  docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d
+
+                  echo "Waiting for backend to start"
+                  wait-on http-get://localhost:3000/explorer --timeout 25000
+                  echo "Backend has started"
+
+                  docker-compose -f docker-compose.yml -f docker-compose.test.yml logs
+
+                  docker logs edrop_backend
+            - name: Cypress E2E tests
+              uses: cypress-io/github-action@v2
+            - name: Stop backend
+            - run: |
+                  # Shut down the testing backend
+                  cd ..
+                  docker-compose -f docker-compose.yml -f docker-compose.test.yml down
+                  exit $EXIT
+            - env:
+                  APP_EMAIL_API_KEY: ${{ secrets.APP_EMAIL_API_KEY }}
+                  SHOPIFY_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}
